### ISSUE TITLE
Blinks in idles

### ISSUE THREAD

**Issue by widdershins** [talkr-app/gif-talkr#1]
When the avatar is not talking it would be nice if she had some kind of idle animations - she might blink or raise her eye brows from time to time. My own interest in this relates to chatbots, where there will be quiet moments between exchanges - and this kind of thing gives avatars more life.

**Comment by talkr-app** [comment]
Check out commit 24db38def9cda936d52d392aa390292b201fcace

The setup_blinks_and_eyebrows function in example.js shows how to use the new system . Feedback welcome!
