### ISSUE TITLE
iOS webkit crash on libgif-js:load after multiple GIF files

### ISSUE THREAD

**Issue by talkr-app** [talkr-app/gif-talkr#2]
Calling the libgif load() function on multiple gif files will eventually crash iOS webkit based browsers like chrome or safari.

This occurs in both buzzfeed/libgif-js and talkr-app/gif-talkr, and is likeley a bug in webkit's canvas implementation.  You can't reproduce the problem on desktop browsers, or Android, and the number of gif files loaded (12 or so) is not sufficient to cause out-of memory problems on iOS.  Reproduced on iOS 10.3.3 and iOS 11 Beta.

On chrome, you get "Aw Snap", while one safari, you get "A problem occurred with this webpage so it was reloaded".  This crashes the javascript console/debugger, so it is very tricky to troubleshoot.

There isn't much to do about this other than hope Apple fixes this issue, and keep the number of active, loaded SuperGif objects to a minimum.  Below is some HTML that reproduces the issue:

```
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
    <script src="./libgif.js"></script>
</head>

<body>
    <div id="container">
    </div>
</body>
<script>
var container = document.getElementById("container")

var gif = "https://i.imgur.com/eBzTN0U.gif"
var supArray = []

function addSup(onLoaded) {
    imgElement = document.createElement('img');
    imgElement.src = gif;
    container.appendChild(imgElement);
    var sup = new SuperGif({
        gif: imgElement
    })
    supArray.push(sup);

    sup.load(function() {
        onLoaded();
    })
}

function onSUPLoaded() {
    if (supArray.length < 40) {
        addSup(onSUPLoaded)
    }
}
addSup(onSUPLoaded);
</script>

</html>


```

**Comment by talkr-app** [comment]
webkit has strict requirements for memory usage and will crash when using too much memory.  The above case simply consumes memory until this happens.

Calling sup.destroy() when you are finished using a SuperGif object will internally pause all looping animations, allowing the frame buffer to be cleared with garbage collection.  It will also immediately set the frames array to [] to immediately free the memory.  

Note:  Deleting a parent HTML element is not sufficient for freeing SuperGif memory. You must call destroy() first.

**Comment by zspitzer** [comment]
here is the safari bug https://bugs.webkit.org/show_bug.cgi?id=172533
